name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate version file
        run: |
          echo "{\"version\":\"${{ github.run_number }}\"}" > version.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22


      - name: Create www folder
        run: |
          rm -rf www
          mkdir www
          cp index.html www/
          cp logo.jpg www/
          cp version.json www/

          if [ -f app.js ]; then cp app.js www/; fi
          if [ -f style.css ]; then cp style.css www/; fi
          if [ -f manifest.json ]; then cp manifest.json www/; fi
          if [ -f service-worker.js ]; then cp service-worker.js www/; fi


      - name: Install dependencies
        run: npm install


      - name: Sync Capacitor
        run: npx cap sync android


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21


      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Push-Up APK
          path: android/app/build/outputs/apk/debug/app-debug.apk